[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "macros"] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"  # (Optional) For env file loading
rand_core = "0.9.3"
